# -*- coding: utf-8 -*-
"""Exercício AED.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QXlYqZ6HHPOkeVKctGZkG4BiQ6PCEV_I
"""

from sklearn.datasets import load_breast_cancer
import pandas as pd

# Carregar o dataset
breast_cancer_data = load_breast_cancer()
df = pd.DataFrame(data=breast_cancer_data.data, columns=breast_cancer_data.feature_names)

# Adicionando a variável alvo
df['target'] = breast_cancer_data.target

""" # Exibir as primeiras linhas do dataframe
df.head()

# Resumo estatístico
df.describe() """

import seaborn as sns
import matplotlib.pyplot as plt

""" # Matriz de correlação
plt.figure(figsize=(12,8))
correlation_matrix = df.corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Matriz de Correlação')
plt.show() """

# Matriz de scatterplots
sns.pairplot(df, hue="target", diag_kind="kde")
plt.show()

""" # Boxplots das features
plt.figure(figsize=(15,10))
df_melt = pd.melt(df, id_vars='target', var_name='features', value_name='values')
sns.boxplot(x='features', y='values', hue='target', data=df_melt)
plt.xticks(rotation=90)
plt.show() """